gcp_credentials: ENCRYPTED[9cf993f6cc2ab666aa2d428185257608d065f6468146aaa26d6d2f31e88ed8045d7dd615cd5c7c83d7bcf12578762869]

task:
  name: build
  timeout_in: 60m
  gke_container:
    image: gradle:4.9.0-jdk8
    cluster_name: cirrus-ci-cluster
    zone: us-central1-a
    namespace: default
    cpu: 3
    memory: 4500m
  gradle_cache:
    folder: ~/.gradle/caches
  env:
    GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-XX:+PrintFlagsFinal -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xmx1G -XX:MaxRAMFraction=1 -XX:+HeapDumpOnOutOfMemoryError"
    ARTIFACTORY_PRIVATE_USERNAME: ENCRYPTED[c44a330260ad4a0bf8ba11eb734e364e7fc4c0590298fc9679a2a76a722cfab8de310be429aa5820100ed92a1a2f977e]
    ARTIFACTORY_PRIVATE_PASSWORD: ENCRYPTED[bae07da73899605302d26c3865cdc68d1895c9feb66466f5f70bd53de2361e24f7f721ced947aa270bab1d134f56ad4c]
  script:
    - printenv
    - java -version
    - gradle build --no-daemon --build-cache -Ptime-tracker --parallel -DbuildNumber=$CIRRUS_BUILD_ID -Pofficial=true
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - rm -f ~/.gradle/caches/build-cache-1/cache.properties
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete
